### ISSUE TITLE
xml中生成的sql代码重复

### ISSUE THREAD

**Issue by pdkst** [chuntungho/mybatis-builder#1]
- 1.0.2重复数量是三份相同代码

- 1.0.3重复数量是两份
使用maven插件```mybatis generator```也会出现这个bug

**Comment by chuntungho** [comment]
自动合并的原理是通过注释（@mbg.generated）标识自动生成的元素，如果原来的代码不包含这个注释，就会当作自定义内容，会叠加在自动生成的代码上。
避免生成重复有两种方式：新的代码使用该工具生成，或在旧的代码增加注释@mbg.generated。
如果不是该种情况，麻烦贴一下重复的代码，我这边分析一下具体原因。

**Comment by pdkst** [comment]
我在新建的项目里生成时没有问题的，但是原先的老项目配置比较混乱我也没搞清楚问题在哪里，```mybatis generator```也是这个问题、```generator mybatis code```插件生成不会出现这种个问题，公司项目不太方便贴代码，非常感谢你的响应~

**Comment by chuntungho** [comment]
客气了，谢谢你的参与。
从代码可维护性考虑，自动生成的代码需要注释说明，且不建议修改自动生成的代码。

**Comment by pdkst** [comment]
~
