### ISSUE TITLE
和Lombok结合使用问题

### ISSUE THREAD

**Issue by icodeeeee** [chuntungho/mybatis-builder#3]
生成的代码中部分字段未遵循驼峰命名比如p_id字段
` 
        if (record.getpId() != null) {
            sql.SET("p_id = #{record.pId,jdbcType=INTEGER}");
        }`
而Lombok生成的是
`if (record.getPId() != null) {
            sql.SET("p_id = #{record.pId,jdbcType=INTEGER}");
        }`

**Comment by chuntungho** [comment]
应该是lombok插件生成getter不符合驼峰规则，尽量避免这种情况，可自定义字段生成规则，重命名为pidh或id

**Comment by chuntungho** [comment]
no fix
