### ISSUE TITLE
‘Copy as Executable SQL’ have  a bug

### ISSUE THREAD

**Issue by CNAHYZ** [chuntungho/mybatis-builder#4]
`2020-06-23 10 : 39 : 21.367 [ DEBUG ] nm.examResult.listExamResultExport - ==> Preparing : SELECT * FROM (SELECT 		*  	FROM 		exam_result_data a  	WHERE 		op_orgnz_id LIKE concat(?, '%' )  		AND date_format( exam_date, '%Y-%m-%d' ) >= ?  		AND ? >= date_format( exam_date, '%Y-%m-%d' )  	) erd 	LEFT JOIN student_info si ON erd.stu_id = si.stu_id  WHERE 	si.stu_id IS NOT NULL  GROUP BY 	erd.stu_id, 	erd.SUBJECT, 	erd.exam_date  ORDER BY 	erd.exam_date DESC, 	CONVERT ( erd.stu_name USING gbk ) ASC
2020-06-23 10:39:21.367  [DEBUG] nm.examResult.listExamResultExport - ==> Parameters: xxxxjx(String), 2020-06-23(String), 2020-06-23(String)
2020-06-23 10:39:21.387  [DEBUG] nm.examResult.listExamResultExport - <==      Total: 0`

### this will copy as :
![图片](https://user-images.githubusercontent.com/33870926/85355981-5a8dd380-b540-11ea-9aef-f984003d64e9.png)

**Comment by CNAHYZ** [comment]
The above SQL statement is simplified

**Comment by chuntungho** [comment]
fixed for Windows
