### ISSUE TITLE
Rename field

### ISSUE THREAD

**Issue by erengong** [chuntungho/mybatis-builder#5]
The perfect plugin! Hope to add a feature:'Rename field', just like'Rename domain'.
![image](https://user-images.githubusercontent.com/30641365/106122575-d5ccfd00-6193-11eb-82e6-a4852a14a67d.png)
![image](https://user-images.githubusercontent.com/30641365/106122665-ebdabd80-6193-11eb-94b4-3f09bfa6c486.png)

**Comment by chuntungho** [comment]
Thanks for your suggestion, it will be available in the next release.
