### ISSUE TITLE
多次反向生成时，中文乱码

### ISSUE THREAD

**Issue by luqil** [chuntungho/mybatis-builder#7]
多次反向生成时Mapper文件，自定义方法注释中文乱码。
windows环境，文件编码为UTF-8,换行法为LF
![image](https://user-images.githubusercontent.com/33475522/128329166-33754086-0b8c-461f-9aca-611ebf701fba.png)
XML文件内中文正常。

建议可以指定生成文件的换行符，不是默认和系统一致。

**Comment by luqil** [comment]
Bean生成注释时，字符串是否可以把类型加上，如: varchar(32)

**Comment by chuntungho** [comment]
fixed in v1.2.2
