### ISSUE TITLE
生成Mapper.java接口重复问题;

### ISSUE THREAD

**Issue by gimishi** [chuntungho/mybatis-builder#8]
您好, 我使用"Run Mybatis Generator" 生成代码时, 出现重复生成Mapper.java中的接口问题. 
麻烦您查看一下, 谢谢.

**Comment by chuntungho** [comment]
是接口文件重复，还是接口方法重复？
接口方法需要有注释@mbg.generated 才会自动合并。

**Comment by gimishi** [comment]
您好
1. 接口方法重复.&nbsp;
2. ***@***.***&nbsp;是有的, 后面跟着时间的;


谢谢.
&nbsp;

石佩刚 (Gimi.Shi)
手机：159 9475 1880
基恩王位置服务平台
http://gnss.wang


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chuntungho/mybatis-builder] 生成Mapper.java接口重复问题; (#8)





 
是接口文件重复，还是接口方法重复？
 ***@***.*** 才会自动合并。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gimishi** [comment]
&nbsp;

石佩刚 (Gimi.Shi)
手机：159 9475 1880
基恩王位置服务平台
http://gnss.wang


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chuntungho/mybatis-builder] 生成Mapper.java接口重复问题; (#8)





 
是接口文件重复，还是接口方法重复？
 ***@***.*** 才会自动合并。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gimishi** [comment]
而且model类的一些手工注解也会丢失:  @DateTimeFormat

**Comment by chuntungho** [comment]
> 而且model类的一些手工注解也会丢失: @DateTimeFormat

model不支持自定义注解，每次都会被覆盖

**Comment by chuntungho** [comment]
fixed in v1.2.2
